#!/bin/bash
number=$(python /root/scripts/get.py)
if [ $number -lt 5 ];
then
        STATUS="0"
        echo "OK - Number of Containers."
else
        echo "CRITICAL - Number of Containers."
        STATUS="2"
fi

exit $STATUS
