#!/bin/bash
number=$(sudo python /root/scripts/get.py)
if [ $number -lt 5 ];
then
        STATUS="0"
        echo "OK - Number of Containers: $number"
else
        echo "CRITICAL - Number of Containers: $number"
        STATUS="2"
fi

exit $STATUS
